

library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(janitor)
###########################################################################
#decide on altprey1 & altprey2 for all ncc predators--------
###########################################################################

combined_guildfiles<-read.csv(outputFile, row.names = NULL) %>% 
  clean_names() %>% 
  rename(sem_name=se_mnode) %>%
  mutate(across(where(is.character), tolower))      
head(combined_guildfiles)

combined_guildfiles %>% filter(latest_guild=="08.predbirdncc")



nccpred <- combined_guildfiles %>% 
  filter(
    is.na(exclusion_reason) | exclusion_reason == "notsalmonpred_or_grouped",
    grepl("08|09|10|11", latest_guild)
  ) %>% 
  mutate(
    altprey1 = case_when(
      # Focal Chinook
      grepl("killer.whale", indicator) ~ "chin",
      
      # Early-run River / Estuary Target
      grepl("allsealionsbonn", indicator) ~ "eulachon",
      
      # Seabirds (Guild 08)
      grepl("08\\.predbirdncc|peli|tern|murre|corm|alcid|shrw|shearwater|grebe", indicator) ~ "market_squid",
      
      # Invertebrate / Planktivorous Feeders
      grepl("hake|rockfish|chilipepper|mackerel|chinook abundance", indicator) ~ "krill",
      
      # Standardized Hake Primary (Marine Mammals & Demersal Predators)
      .default = "hake"
    ),
    
    altprey2 = case_when(
      # Focal Salmonid Predators
      grepl("killer.whale|allsealionsbonn|allsealionsemb", indicator) ~ "salmonids",
      
      # ANCHOVY PREFERRERS
      # - California Sea Lions
      # - Seabirds (Guild 08)
      # - Pelagic Mackerels, Rockfish, & Adult Chinook Stocks
      grepl("californian_s_l", indicator) ~ "anchovy",
      grepl("08\\.predbirdncc|peli|tern|murre|corm|alcid|shrw|shearwater|grebe", indicator) ~ "anchovy",
      grepl("rockfish|chilipepper|mackerel|chinook abundance", indicator) ~ "anchovy",
      
      # HAKE PREFERRERS (Adult Hake diet)
      grepl("hake", indicator) ~ "anchovy",
      
      # HERRING PREFERRERS (Default for remaining mammals & demersals)
      # - Steller Sea Lions, Harbor Seals, Fur Seals, Harbor Porpoise
      # - Lingcod, Halibut, Skates, Dogfish
      .default = "herring"
    )
  ) %>% 
  arrange(altprey1, altprey2)

# Display complete output
print(as_tibble(nccpred), n = Inf)

#save prey assignments----------
write.csv(nccpred, file.path(outputDir, "nccpred_altprey_assigned.csv"), row.names = FALSE)

######################################################
#identify prey data series-------

rankedIndicators<-read.csv( file.path(outputDir, "rankedIndicators.csv"), row.names = NULL)

rankedIndicators %>%
  filter(grepl("ChinAbundSnakeFall|HakeAge5Plus_2025|Tspin|Euph|marketsquid_GAM_2025|anchovy_GAM_2025|abundHerring", rankedIndicators))

library(dplyr)
library(stringr)

# Load ranked indicators file generated by the DFA pipeline
rankedIndicators <- read.csv(file.path(outputDir, "rankedIndicators.csv"), row.names = NULL)

# Filter for your specific target prey indicators
target_prey_matches <- rankedIndicators %>% 
  filter(
    str_detect(
      rankedIndicators, 
      regex("ChinAbundSnakeFall|HakeAge5Plus_2025|Tspin|Euph|marketsquid_GAM_2025|anchovy_GAM_2025|abundHerring", ignore_case = TRUE)
    )
  )

print(target_prey_matches)


library(dplyr)
library(tidyr)

# Load wide DFA time series
clusDataDFA_wide <- read.csv(file.path(outputDir, "clusDataDFA_wide_1996_2025.csv"))

# Specify target DFA and smoothed columns from your output
target_prey_cols <- c(
  "X09.PredFishNCC_DFA1",      # chin
  "X09.PredFishNCC_b_DFA1",    # hake
  "X01.ZooPreyNCC_NHL_DFA1",   # krill (NCC)
  "X12.ZooPreyAK_DFA1",        # krill (AK)
  "X04.CompFishNCC_smoothed",  # market_squid
  "X05.ForageFishNCC_0_smoothed", # anchovy
  "X13.FishPreyAK_b_DFA1"      # herring
)

# Keep only columns present in the wide data frame
available_target_cols <- intersect(names(clusDataDFA_wide), target_prey_cols)

# Run completeness check (1996 to 2025)
completeness_summary <- clusDataDFA_wide %>% 
  select(Year, all_of(available_target_cols)) %>% 
  pivot_longer(cols = -Year, names_to = "DFA_name", values_to = "value") %>% 
  group_by(DFA_name) %>% 
  summarize(
    total_years    = n(),
    valid_years    = sum(!is.na(value)),
    missing_years  = sum(is.na(value)),
    start_year     = min(Year[!is.na(value)], na.rm = TRUE),
    end_year       = max(Year[!is.na(value)], na.rm = TRUE),
    missing_list   = ifelse(missing_years > 0, paste(Year[is.na(value)], collapse = ", "), "None")
  )

print(completeness_summary)


print(completeness_summary)

# DFA_name                     total_years valid_years missing_years start_year end_year missing_list                      
# 1 X01.ZooPreyNCC_NHL_DFA1               30          24             6       1998     2021 1996, 1997, 2022, 2023, 2024, 2025
# 2 X04.CompFishNCC_smoothed              30          27             3       1998     2024 1996, 1997, 2025                  
# 3 X05.ForageFishNCC_0_smoothed          30          27             3       1998     2024 1996, 1997, 2025                  
# 4 X09.PredFishNCC_DFA1                  30          30             0       1996     2025 None                              
# 5 X09.PredFishNCC_b_DFA1                30          27             3       1998     2024 1996, 1997, 2025                  
# 6 X12.ZooPreyAK_DFA1                    30          28             2       1996     2023 2024, 2025                        
# 7 X13.FishPreyAK_b_DFA1                 30          28             2       1996     2023 2024, 2025      



#########################################


#set up prey database------------
library(dplyr)
library(tidyr)
library(lubridate)
library(imputeTS)

# ---------------------------------------------------------------------------
# Load and Process Eulachon Datasets
# ---------------------------------------------------------------------------
# Annual Run Index (Reconstructed Lbs)
eulachon_annual <- read.csv(
  "C:/Users/Lisa.Crozier/Documents/Marine survival/SEM-DFO-LisaXP/copilot/outputs_csl_cr/eulachon_master_index_lbs_1993_2024.csv",
  row.names = NULL
) %>%
  select(year, eulachon_lbs_reconstructed) %>%
  arrange(year)

eulachon_annual$eulachon_lbs_interp <- na_interpolation(eulachon_annual$eulachon_lbs_reconstructed)

# Weekly Overlap Index (Active Chinook Window)
eulachon_weekly <- read.csv(
  "C:/Users/Lisa.Crozier/Documents/Marine survival/SEM-DFO-LisaXP/copilot/outputs_csl_cr/master_estuary_2wklagweekly_all_species_1998_2024.csv",
  row.names = NULL
) %>%
  group_by(year) %>%
  summarise(eulachon_during_chinook = sum(eulachon_final[is_chinook_active], na.rm = TRUE), .groups = "drop") %>%
  select(year, eulachon_during_chinook)

# Combine and apply Log + Z-score scaling
eulachon_clean <- full_join(eulachon_weekly, eulachon_annual %>% select(year, eulachon_lbs_interp), by = "year") %>%
  rename(Year = year) %>%
  mutate(
    # Primary index: Weekly overlap
    eulachon_weekly_scaled = as.vector(scale(log1p(eulachon_during_chinook))),
    # Secondary index: Annual reconstructed run size
    eulachon_annual_scaled = as.vector(scale(log1p(eulachon_lbs_interp)))
  )

# ---------------------------------------------------------------------------
# Load DFA / Smoothed Prey Dataset and Merge
# ---------------------------------------------------------------------------
clusDataDFA_wide <- read.csv(file.path(outputDir, "clusDataDFA_wide_1996_2025.csv"))

# Build final target prey dataset
altprey_wide <- clusDataDFA_wide %>%
  select(
    Year,
    chin         = X09.PredFishNCC_DFA1,
    hake         = X09.PredFishNCC_b_DFA1,
    krill        = X12.ZooPreyAK_DFA1,
    market_squid = X04.CompFishNCC_smoothed,
    anchovy      = X05.ForageFishNCC_0_smoothed,
    herring      = X13.FishPreyAK_b_DFA1
  ) %>%
  left_join(
    eulachon_clean %>% select(Year, eulachon = eulachon_weekly_scaled, eulachon_annual = eulachon_annual_scaled),
    by = "Year"
  ) %>%
  arrange(Year)

# Export complete prey dataset--------
write.csv(altprey_wide, file.path(outputDir, "altprey_wide_1996_2025.csv"), row.names = FALSE)

head(altprey_wide)
