# ==============================================================================
# Script: 02_goal3_generate_table5_from_saved_data.R
# Directory: Rcode_for_paper/04_goal3_interaction_analysis/
# Purpose: Generate Table 5 directly from saved CSVs (No Model Re-runs Required)
# Output: Rcode_for_paper/Routput_for_paper/tables/
# ==============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(gt)
  library(stringr)
})

# ------------------------------------------------------------------------------
# STEP 0: SETUP PATHS & LOAD MASTER CROSSWALK
# ------------------------------------------------------------------------------
proj_dir     <- getwd()
master_out   <- file.path(proj_dir, "Rcode_for_paper", "Routput_for_paper")
tbl_out_dir  <- file.path(master_out, "tables")
data_out_dir <- file.path(master_out, "data")

dir.create(tbl_out_dir, showWarnings = FALSE, recursive = TRUE)

# Input files generated by previous run
summaries_path <- file.path(data_out_dir, "Goal3_Model_Summaries_Comparison.csv")
params_path    <- file.path(data_out_dir, "Goal3_All_Parameter_Estimates.csv")

if (!file.exists(summaries_path) || !file.exists(params_path)) {
  stop("Missing required input CSVs in: ", data_out_dir)
}

# Load Master Crosswalk for clean LisaName labels
crosswalk_path <- file.path("metadata", "master_name_crosswalk.csv")
if (!file.exists(crosswalk_path)) stop("Missing master crosswalk at: ", crosswalk_path)

master_crosswalk <- read.csv(crosswalk_path, stringsAsFactors = FALSE)

# Build Crosswalk Mapping Dictionary
lookup_dict     <- setNames(master_crosswalk$LisaName, tolower(master_crosswalk$dfa_cols))
lookup_dict_raw <- setNames(master_crosswalk$LisaName, tolower(master_crosswalk$DFAname))
lookup_dict     <- c(lookup_dict, lookup_dict_raw)

get_lisa_name <- function(raw_col) {
  raw_lower <- tolower(raw_col)
  if (raw_lower %in% names(lookup_dict)) {
    return(lookup_dict[[raw_lower]])
  }
  return(raw_col)
}

cat("Loading pre-calculated Goal 3 parameter and summary datasets...\n")

# ------------------------------------------------------------------------------
# STEP 1: READ SAVED RESULTS & IDENTIFY MAIN PREDATOR SLOPES
# ------------------------------------------------------------------------------
summary_results <- read_csv(summaries_path, show_col_types = FALSE)
all_params_df   <- read_csv(params_path, show_col_types = FALSE)

# Isolate main predator slopes from the parameters file to verify top-down direction
pred_slopes <- all_params_df %>%
  filter(term_type == "Main Predator Effect") %>%
  select(pair_id, model_type, lhs, term, est) %>%
  pivot_wider(
    names_from = lhs,
    values_from = est,
    names_prefix = "beta_"
  )

# Merge predator slopes back to summaries if not present
if (!"beta_ncc_pred" %in% names(summary_results)) {
  # Map lhs target names dynamically
  target_ncc_name <- unique(all_params_df$lhs)[1] # x07_dfa_cpue_intsprjunhw
  target_ak_name  <- unique(all_params_df$lhs)[2] # x16_sar
  
  slopes_clean <- all_params_df %>%
    filter(term_type == "Main Predator Effect") %>%
    group_by(pair_id, model_type) %>%
    summarise(
      beta_ncc_pred = mean(est[lhs == target_ncc_name], na.rm = TRUE),
      beta_ak_pred  = mean(est[lhs == target_ak_name], na.rm = TRUE),
      .groups = "drop"
    )
  
  summary_results <- summary_results %>%
    left_join(slopes_clean, by = c("pair_id", "model_type"))
}

# ------------------------------------------------------------------------------
# STEP 2: APPLY TOP-DOWN FILTERING (EXCLUDE POSITIVE MAIN PREDATOR SLOPES)
# ------------------------------------------------------------------------------
cat("Filtering out models with positive main predator coefficients (beta > 0)...\n")

filtered_summaries <- summary_results %>%
  # Keep ONLY models where main predator slopes are non-positive (top-down predation)
  filter(
    (is.na(beta_ncc_pred) | beta_ncc_pred <= 0) & 
      (is.na(beta_ak_pred)  | beta_ak_pred  <= 0)
  )

cat(sprintf("Retained %d / %d model runs matching top-down criteria (beta <= 0).\n", 
            nrow(filtered_summaries), nrow(summary_results)))

# ------------------------------------------------------------------------------
# STEP 3: CONSTRUCT EXPLICIT TREATMENT COLUMNS & MAP LISANAME
# ------------------------------------------------------------------------------
table5_prepared <- filtered_summaries %>%
  # Apply clean LisaName mapping
  mutate(
    ncc_pred_clean = sapply(ncc_predator, get_lisa_name),
    ak_pred_clean  = sapply(ak_predator,  get_lisa_name),
    
    # Construct explicit treatment columns showing exact operator/covariate
    ncc_treatment = case_when(
      model_type == "Thermal Moderation (Pred*SST)"  ~ paste0(ncc_pred_clean, " × SST"),
      model_type == "AltPrey Moderation (Pred*Prey)" ~ paste0(ncc_pred_clean, " × AltPrey"),
      TRUE                                           ~ "None (Main Effect Only)"
    ),
    
    ak_treatment = case_when(
      model_type == "Thermal Moderation (Pred*SST)"  ~ paste0(ak_pred_clean, " × SST"),
      model_type == "AltPrey Moderation (Pred*Prey)" ~ paste0(ak_pred_clean, " × AltPrey"),
      TRUE                                           ~ "None (Main Effect Only)"
    )
  ) %>%
  # Rank top 5 models within each structural group by AIC
  group_by(model_type) %>%
  slice_min(order_by = aic, n = 5, with_ties = FALSE) %>%
  ungroup() %>%
  arrange(aic) %>%
  mutate(delta_aic_overall = round(aic - min(aic), 2))

# Save Filtered Summary CSV
write_csv(table5_prepared, file.path(data_out_dir, "Goal3_Model_Summaries_Comparison_Filtered.csv"))

# ------------------------------------------------------------------------------
# STEP 4: RENDER GT MANUSCRIPT TABLE 5
# ------------------------------------------------------------------------------
table5_gt <- table5_prepared %>%
  select(
    model_type, 
    ncc_pred_clean, 
    ncc_treatment, 
    ak_pred_clean, 
    ak_treatment, 
    aic, 
    delta_aic_overall, 
    cfi, 
    cpue_r2, 
    sar_r2
  ) %>%
  gt(groupname_col = "model_type") %>%
  tab_header(
    title = md("**Table 5. Model Evaluation: Baseline DAG 1A vs. Non-Linear Interaction Structures**"),
    subtitle = "Standardized evaluation on complete 1998–2021 observations (restricted to top-down main predator effects: β ≤ 0)"
  ) %>%
  cols_label(
    ncc_pred_clean    = md("**NCC Predator**"),
    ncc_treatment     = md("**NCC Moderation Term**"),
    ak_pred_clean     = md("**AK Predator**"),
    ak_treatment      = md("**AK Moderation Term**"),
    aic               = md("**AIC**"),
    delta_aic_overall = md("**ΔAIC**"),
    cfi               = md("**CFI**"),
    cpue_r2           = md("**R² (CPUE)**"),
    sar_r2            = md("**R² (SAR)**")
  ) %>%
  cols_align(align = "center", columns = c(aic, delta_aic_overall, cfi, cpue_r2, sar_r2)) %>%
  cols_align(align = "left", columns = c(ncc_pred_clean, ncc_treatment, ak_pred_clean, ak_treatment)) %>%
  fmt_number(columns = c(aic, delta_aic_overall, cfi, cpue_r2, sar_r2), decimals = 2) %>%
  tab_options(
    table.font.size = px(9),
    heading.title.font.size = px(11.5),
    column_labels.font.weight = "bold",
    row_group.font.weight = "bold"
  )

# Save Formatted Outputs
gtsave(table5_gt, file.path(tbl_out_dir, "Table5_Model_Comparison_Baseline_vs_Interactions.html"))
gtsave(
  data     = table5_gt,
  filename = file.path(tbl_out_dir, "Table5_Model_Comparison_Baseline_vs_Interactions.png"),
  vwidth   = 1250,
  vheight  = 650
)

message("Table 5 regenerated successfully without re-running models! Saved to: ", tbl_out_dir)
